######################################
#            MySql section           #
######################################
MySQL:
    database:
        username: username # Your database username
        password: password # Your database password
        database: database # Your database name
        mcmmoPrefix: mcmmo_ # The mcmmo table prefix in your database
    server:
        port: 3306 # Your database's port number
        address: localhost # Your database's address (IP)
######################################
#        Rewards setup section       #
######################################
# plvl lines up to name, please keep it exact
rSetup:
    plvl:
        - 1
    name: 
        - example
######################################
#           Rewards section          #
######################################
# example
#   rewardName:
#       requirements: yes/no # please only use one requirement at a time
#       oneStatAt: 1 # required
#       twoStatsAt: 5 #  required
#       threeStatsAt: none #  required, none means there is no requirement for this stage
#       allStatsAt: none # required, none means there is no requirement for this stage
#       commands: /feed {player}/heal {player}/give {player} 56 1 
# no spaces between commands, for items please use item ID and not name
# accepted modifiers are {player} for the players name, 
###
rewards:
    example:
        requirements: no # please only use one requirement at a time
        oneStatAt: none # required
        twoStatsAt: none #  required
        threeStatsAt: none #  required, none means there is no requirement for this stage
        allStatsAt: none # required, none means there is no requirement for this stage
        commands: /msg {player} you have been given the reward example 