name: LLFRewards
main: com.llfrealms.LLFRewards.LLFRewards
version: 1.5

commands:
    llfsave:
       description: save config.
       usage: /<command>
    llfload:
       description: reload config.
       usage: /<command>
    llfadd:
       description: add rewards to the config.
       usage: /<command> {rewardName} {powerlevel} r:{requirements yes/no} r1:{req1} r2:{req2} r3:{req3} r4:{req4} {commands}
permissions:
    jack.message:
        description: message!
        default: false